### ISSUE TITLE
Unappropriate sed delimeter in configure file

### ISSUE THREAD

**Issue by essemenoff** [symengine/symengine.R#102]
Hello SymEngine developers,

During R-package installation I catched next error
```
sed: -e expression #1, char 75: unknown option to `s'
```
I found sed delimeter is set to colon in configure file of R-package archive

configure, lines 171-173
```
    sed "s:@@@PKG_LIBS@@@:$PKG_LIBS_VALUE:g" | \  
    sed "s:@@@PKG_CPPFLAGS@@@:$PKG_CPPFLAGS_VALUE:g" |   
    sed "s:@@@DO_UPSTREAM@@@:$DO_UPSTREAM:g" \  
```

It occurs if PKG_LIBS_VALUE, PKG_CPPFLAGS_VALUE contains text with multiple path.
Example of PKG_LIBS_VALUE
```
-Wl,-rpath,/my/path/GMP/lib:/my/path/MPFR/lib upstream/symengine/libsymengine.a /my/path/GMP/lib/libgmp.so /my/path/MPFR//lib/libmpfr.so

```

I changed colon to vertical slash
```
    sed "s|@@@PKG_LIBS@@@|$PKG_LIBS_VALUE|g" | \  
    sed "s|@@@PKG_CPPFLAGS@@@|$PKG_CPPFLAGS_VALUE|g" |   
    sed "s|@@@DO_UPSTREAM@@@|$DO_UPSTREAM|g" \  
```
and it works.

Could you please fix this issue?

Best wishes,
Semenov Evgenii

**Comment by Marlin-Na** [comment]
Thanks for the report. It will be fixed in #104
