### ISSUE TITLE
Cannot locate correct libraries on linux

### ISSUE THREAD

**Issue by mattfidler** [symengine/symengine.R#107]
This is from a very knowledgeable IT administrator;  I was trying to install on my companies linux HPC and the GMP  / MPFR binaries are wrong. His statement was:

> -- Found GMP: /usr/lib64/libgmp.so  
> -- Found MPFR: /usr/lib64/libmpfr.so  

> is wrong – it should detect the other path that is accessible via LD_LIBRARY_PATH. This is run at installation as part of the cmake process (see symengine/src/upstream/cmake/FindMPFR.cmake) 

> It seems like the developers were/are struggling with this part a lot according to http://cmake.3232098.n2.nabble.com/What-is-the-recommended-ways-to-find-libraries-td7590792.html 

> -- Found GMP: /usr/lib64/libgmp.so  
> -- Found MPFR: /usr/lib64/libmpfr.so  

> is wrong – it should detect the other path that is accessible via LD_LIBRARY_PATH. This is run at installation as part of the cmake process (see symengine/src/upstream/cmake/FindMPFR.cmake) 
 
>It seems like the developers were/are struggling with this part a lot according to http://cmake.3232098.n2.nabble.com/What-is-the-recommended-ways-to-find-libraries-td7590792.html 

I  think that data.table uses `pkgconfig`, that may work here?

https://github.com/Rdatatable/data.table/blob/97c96b2aacaacc0ae0e2df7b5ed85124da5eb524/configure#L24-L47

Is there a way to over-ride the detection and specify them manually?

**Comment by isuruf** [comment]
`LD_LIBRARY_PATH` is for the dynamic loader. `LIBRARY_PATH` is used by most compilers and cmake only looks at paths that the compiler recognizes. You can set `LIBRARY_PATH` if the compiler supports that. Or use `CMAKE_PREFIX_PATH` env variable which is supported by cmake for all compilers.

**Comment by mattfidler** [comment]
Thanks;  I will try with this
