### ISSUE TITLE
Fatal error on Windows 10

### ISSUE THREAD

**Issue by jrproctor** [symengine/symengine.R#112]
I installed SymEngine from source on Windows 10, and I get a fatal error when executing any symengine code in both RStudio and the R console.

Steps to produce:
```
library(symengine)
Symbol("x")
```

My session info:
```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8   
[3] LC_MONETARY=English_Canada.utf8 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] symengine_0.1.6

loaded via a namespace (and not attached):
[1] compiler_4.2.0  tools_4.2.0     rstudioapi_0.13 crayon_1.5.1    Rcpp_1.0.8.3   
```

**Comment by Marlin-Na** [comment]
Thanks for reporting. Looks like that it is also failing on CRAN now. I will look into this.

**Comment by isuruf** [comment]
R 4.2.0 switched to UCRT builds and we need to rebuild symengine and gmp using the new toolchain.

**Comment by Marlin-Na** [comment]
@jrproctor This is fixed on master branch, you can now install from source from github. You will need to install [Rtools42](https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html) to build the package. I also submitted it to CRAN, but it might take a few days to process.

**Comment by jrproctor** [comment]
Thanks! Confirming that I installed from github and did not encounter the error that I reported earlier.
