### ISSUE TITLE
Load failed due undefined symbol error 

### ISSUE THREAD

**Issue by imsavin** [symengine/symengine.R#122]
Hello! I have problem with installation of "symegine" R package.

It's looks like compilation goes ok, but when R tryes to load package it fails with  this error:
```
Error: package or namespace load failed for 'symengine':
 .onLoad failed in loadNamespace() for 'symengine', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/isavin/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-symengine/00new/symengine/libs/symengine.so':
  /home/isavin/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-symengine/00new/symengine/libs/symengine.so: undefined symbol: basic_abs
Error: loading failed
Execution halted
ERROR: loading failed

```

SymEngine 0.10.1
R 4.2.0

full log of symengine package installation below:
[R-symengine-installation.log](https://github.com/symengine/symengine.R/files/11998717/R-symengine-installation.log)

**Comment by Marlin-Na** [comment]
Thanks for the issue. Can you help check if https://github.com/symengine/symengine.R/pull/123 works for you?

**Comment by imsavin** [comment]
It works, thank you! Installed package seamlessly
