### ISSUE TITLE
Provide S4 method for sum and prod

### ISSUE THREAD

**Issue by Marlin-Na** [symengine/symengine.R#27]

**Comment by mattfidler** [comment]
S4 is inefficient. Maybe consixer R6?

**Comment by Marlin-Na** [comment]
@mattfidler R6/RC have reference semantics and do not really apply here. Even we are using R6 for wrapping the SymEngine objects, we still need to implement binding for operators and math functions in S3/S4, which do not really bring us any benefit here.

That being said, the alternative to S4 should be S3 instead of R6 or RC. The main concern for S4's performance is that the dispatch could be slower than pure function calls, and S4's dispatch used to be slower than S3 (though it is no longer true for the latest versions of R).

For this package, I have limited S4 usage only for overloading base R functions and have implemented various functions such as type checking in C++ for performance improvement.

**Comment by mattfidler** [comment]
Thank you for your response.
