### ISSUE TITLE
Are you eventually going to submit symengine.R to CRAN?

### ISSUE THREAD

**Issue by mattfidler** [symengine/symengine.R#34]
I want to be sure before investing time to use the package in my CRAN package.

**Comment by Marlin-Na** [comment]
Yes, I am planning to submit it on CRAN, though currently I do not have a specific timeline for it. I am interested to know your use case -- this could help improve this package and I may help with the integration with your package.

**Comment by mattfidler** [comment]
Currently I use sympy for forward sensitivity analysis in `RxODE`.  All the pieces should be there for `SymEnigne`.  I do wonder about arbitrary derivatives, which sympy supports and I make use of.

Currently the ODEs are expressed in a mini-language that is compatible with R parsers

```
RxODE({
d/dt(x)=-k*x
})
```

I currently convert `d/dt` to python compatible variables.

**Comment by mattfidler** [comment]
I will also  be using the `expand` as well as the simple derivatives.

**Comment by mattfidler** [comment]
One of the things I'm not sure how to do in `SymEngine` is to load a bunch of arbitrary expressions into memory and then perform derivative operations on the expressions.

**Comment by mattfidler** [comment]
I looked through and I saw `Symbol` and `use_vars` but no `Function` or `use_function` variable

**Comment by Marlin-Na** [comment]
> One of the things I'm not sure how to do in SymEngine is to load a bunch of arbitrary expressions into memory and then perform derivative operations on the expressions.

I assume that the expressions you are using are quoted R expression? Then I am planning to implement the conversion method from R expression to SymEngine objects. You can see it works for simple formula.

> I looked through and I saw Symbol and use_vars but no Function or use_function variable

Yes, I am planning to implement them.

**Comment by mattfidler** [comment]
> I assume that the expressions you are using are quoted R expression? Then I am planning to implement the conversion method from R expression to SymEngine objects. You can see it works for simple formula.

It is true that it works for a simple formula.  

In `sympy` I assigned each expression to python variables and then accessed them later.  I went line-by-line through a RxODE equation and evaluated the converted R(xODE)->python expression and then accessed the variables later.  This effectively substituted all the pre-defined variables into a long expression that could be accessed later to build a RxODE model with forward sensitivities calculated.

With the assigned python variables I took the derivatives and added the expressions for the forward sensitivities.

I don't see a method to assign variables in `symengine`;  Expressions are OK too, but I'm unsure if they will keep some of the expressions assigned to use in later calculations.

> Yes, I am planning to implement them.

Thank you.  

I use that for some arbitrary functions.  It also will allow me to determine if conditional expressions (i.e. if/else branching) depends on parameters that I am taking the forward sensitivity of by converting `R` expressions like `==` to `rxEq` for instance.  

I am assuming that `==` and other similar expressions are currently not supported in arbitrary derivatives such as:

```R
A = (c==1)*x + x^2
```
Since I get:

```
> symengine::D(((c ==1)*x) ^ 2L - 42L)
Error in c == 1 : 
  comparison (1) is possible only for atomic and list types
```

I assuming by using `2L`  could possibly change the calculation routines internally?  It did for sympy, but that could be due to parsing in general (not sure).

**Comment by Marlin-Na** [comment]
> I don't see a method to assign variables in symengine; Expressions are OK too, but I'm unsure if they will keep some of the expressions assigned to use in later calculations.

I am not sure whether I understand it correctly, but you can assign SymEngine object to a R variable, for example:
```
var1 <- Symbol("x")
var2 <- var1 ^ 3L
```
You can also store them in a list or an environment and refer them later.
```
lst <- list()
lst["var1"] <- S(~ (x + y) ^ 2)
lst["var2"] <- expand(lst["var1"])
D(lst["var2"], ~x)
```

> I use that for some arbitrary functions. It also will allow me to determine if conditional expressions (i.e. if/else branching) depends on parameters that I am taking the forward sensitivity of by converting R expressions like == to rxEq for instance.

I guess you are looking for piecewise expressions? I think they are implemented in SymEngine but not yet for in its C wrapper, hence not available in R. Further, the `==` and `!=` functions are for testing the equality of SymEngine objects -- they return `TRUE` or `FALSE` instead of a SymEngine objects. Possibly in future we can have functions such as `Eq`, `Neq` and `Piecewise`.

Or maybe you can defer the evaluation with a function like this:

```
expr <- S(~ (a * x) ^ 2L - 42L)
Diff_conditional <- function(expr, name, c) {
    if (type(c) == "Integer" && as.integer(c) == 1L) {
        return(D(subs(expr, "a", S(1L)), name))
    }
    else
        return(D(subs(expr, S("a"), S(0)), name))
}
Diff_conditional(expr, "x", S(1))
(Mul)	2*x
Diff_conditional(expr, "x", S(0))
(Integer)	0
```

**Comment by Marlin-Na** [comment]
Actually, for the example above, you may also do:

```
expr <- S(~ (condition * x) ^ 2L - 42L)
d <- D(expr, "x")
subs(d, ~ condition, ~ 1)
subs(d, ~ condition, ~ 0)
```

**Comment by mattfidler** [comment]
Thanks @Marlin-Na ;  I agree, and that is what I do.  The only problem is when `condition` depends on `x`.

**Comment by mattfidler** [comment]
Can you do something like

```r
S(saved1 ~ x+3)
```
And then since `saved1` is in memory, you can then evaluate the following:

```r
D(saved1,x)
```

When I try this in the current SymEngine, I get: 

```R
>S(saved1 ~ x+3)
Error in s4basic_parse(x, check_whole_number = TRUE) : 
  Evaluation error: length(x) == 2 is not TRUE.
```

**Comment by mattfidler** [comment]
Perhaps that is what you mean by `const` expressions?

**Comment by Marlin-Na** [comment]
> Can you do something like
> S(saved1 ~ x+3)

Currently `S` only accept formula with right hand side. But I am not clear why not assign the expression to a variable like:

```r
saved <- S(~ x+3)
D(saved, "x")
```

Perhaps I should also mention that it is possible to use backquote in a formula:

```r
var1 <- ~x
var2 <- ~ (a + .(var1))^2

var3 <- ~ (b + {{ expand(S(var2)) }})^2

var2
## ~(a + .(var1))^2
var3
## ~(b + {{ expand(S(var2)) }})^2

S(var2)
## (Pow)	(a + x)^2
S(var3)
## (Pow)	(b + 2*a*x + a^2 + x^2)^2
```

You can see from the above example that I have implemented `.()` (see in `bquote`) and `{{}}` style backquoting. When `S` encounters such cases, it will evaluate the expression enclosed by `.()` or `{{}}` in the environment where the formula is created. I might only keep one of `.()` and `{{}}` backquoting in future.

> Perhaps that is what you mean by const expressions?

I suppose you mean `Constant` object. The `S` function will parse some string as Constants, instead of Symbols, so that I have explicit constructors for them. See the following example:

```r
S("E")
# (Constant)	exp(1)
Constant("E")
# (Constant)	exp(1)
Symbol("E")
# (Symbol)	E

evalf(Constant("E"))
# (RealDouble)	2.71828182845905
evalf(Symbol("E"))
# Error in s4binding_evalf(expr, bits, complex) : 
#  SymEngine exception: Runtime error
```

**Comment by mattfidler** [comment]
> Currently S only accept formula with right hand side. But I am not clear why not assign the expression to a variable like:

That is fine with me.  However, in `sympy` for instance

```python
x = Symbol(x)
y = Symbol(y)
a = (x+y)^2
b = a+x^2
b
```

`b` would have the complete expression.

Since I wrote my routines with `sympy` in mind, it would take a large refactoring to use backquotes to do the same sort of thing.  I think it should be possible to query the parent environment for `symengine` variables and substitute them in, so in R you could have:

```R
var1 <- S(~x)
var2 <- ~ S(~(a + var1)^2)
```

Be acceptable syntax as long as `var1` is in the parent environment.  For me, if that was implemented the refactoring would be smaller.  I could use DSL to do it myself in my package, but I think it would be more efficient and possibly more useful for others if sympy did it by querying the environment in Cpp.  

Do you think that would be a good idea?  If you are unclear on how to do this, I can help with the Rcpp/R code.

**Comment by Marlin-Na** [comment]
> b would have the complete expression.

I am not clear what do you mean by complete expression. But I suppose you can do the same in R. For this part, the R binding has the same design as sympy, symbolic expressions are treated as normal R objects, and math functions and operators are directly supported via dispatch. If you run your example, ‘b’ would certainly be a SymEngine object

**Comment by mattfidler** [comment]
To be more clear, let me show the correct syntax and output in `sympy`:

```python
Python 3.6.5 (default, Jun 28 2019, 22:01:16) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x, y = symbols('x y')
>>> a = (x+y)**2
>>> b = a + x**2
>>> b
x**2 + (x + y)**2
```

See that `b` is `x^2+(x+y)^2`

Now lets try symengine:

```R
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(symengine)
SymEngine Version: 0.4.0
 _____           _____         _         
|   __|_ _ _____|   __|___ ___|_|___ ___ 
|__   | | |     |   __|   | . | |   | -_|
|_____|_  |_|_|_|_____|_|_|_  |_|_|_|___|
      |___|               |___|          

Attaching package: ‘symengine’

The following object is masked from ‘package:stats’:

    D

> x = S(~x)
> y = S(~y)
> a = S(~(x+y)^2)
> b = S(~a+x^2)
> b
(Add)	a + x^2
```

Note that `b` is not expanded or substituted to `x^2+(a+b)^2`

In theory you could lookup `a` in the parent environment and substitute it into the expression as long as it is a symengine object.  With that addition, `symengine` would behave more like `sympy` and for that matter more like `ryacas`

**Comment by mattfidler** [comment]
I do understand of course the back-quoting:

```R
> b = S(~.(a)+x^2)
> b
(Add)	x^2 + (x + y)^2
```
But this would require a larger refactoring on my part and isn't the way that `sympy` works either.

**Comment by isuruf** [comment]
@mattfidler, how about `b = a + S(~x^2)`

**Comment by isuruf** [comment]
Or just, `b = a + x^2`

**Comment by mattfidler** [comment]
Ok, so as long as the objects are defined as a symbol in `symengine` then assignments and other such things would work.

The missing piece for me is then simply allowing arbitrary functions in  #36 (and possibly modifying the derivative table for these functions)

**Comment by Marlin-Na** [comment]
@mattfidler Can you show me an example how would you derive arbitrary function with sympy? I suspect that you want Piecewise expression instead of [Function symbol](https://docs.sympy.org/latest/modules/functions/index.html) in sympy.

**Comment by mattfidler** [comment]
Sure;

I have a function `linearSolvedSystem(x,a,b,c,d,e,f)` that I have calculated derivatives from and sympy has an arbitrary derivative `subs(D(...),xi_=a)` which I then parse and replace with the calculated derivatives.

**Comment by mattfidler** [comment]
The linear solved system changes based on events and steady-state ODE solutions, so it isn't trivial to express as an algebraic solution.

**Comment by mattfidler** [comment]
I also use it to translate `==` to `rxEq()` to check if any of the sensitivities I'm calculating depend on the equality.  If so I can fall back to numeric differences or something similar.

**Comment by isuruf** [comment]
@mattfidler, you can do `g = S("linearSolvedSystem(x,a,b,c,d,e,f)")` and then you can do partial differentiation on `g` w.r.t any variable.

**Comment by mattfidler** [comment]
Thanks @isuruf  that is what I need.

**Comment by mattfidler** [comment]
I will start writing assuming that `symenigne` will be going to CRAN within the next few months.

**Comment by mattfidler** [comment]
I finished porting all the sympy functions in RxODE and dsl to symengine.  @Marlin-Na and @isuruf  is there anything I can do to help you get to cran?

**Comment by Marlin-Na** [comment]
@mattfidler It is good to know that symengine works for your application. Hopefully I will start the process submitting it to CRAN in mid-August. There are still several features that I hope to implement before the first release, as well as additional documentation, vignettes, etc.

**Comment by mattfidler** [comment]
Ok.  If you need help with this let me know @Marlin-Na
