### ISSUE TITLE
lgamma and other more complex functions missing from symengine

### ISSUE THREAD

**Issue by mattfidler** [symengine/symengine.R#37]
```R
library(symengine)
> S(~lgamma(x))
Error in s4basic_parse(x, check_whole_number = TRUE) : 
  Evaluation error: Unable to parse lgamma(x).
```

In `sympy` this is `gammafn`

For my `R`->`sympy` table this is what I have:

```R
rxSymPyFEnv$gammafn <- functionOp("gamma")
rxSymPyFEnv$lgammafn <- functionOp2("log(gamma(", "))")
rxSymPyFEnv$lgamma <- functionOp2("log(gamma(", "))")
rxSymPyFEnv$tetragamma <- functionOp2("psigamma(", ", 2)")
rxSymPyFEnv$pentagamma <- functionOp2("psigamma(", ", 3)")
rxSymPyFEnv$lbeta <- functionOp2("log(beta(", "))")
rxSymPyFEnv$lgamma1p <- functionOp2("log(gamma((", ")+1))")
rxSymPyFEnv$cospi <- functionOp2("cos(pi * (", "))")
rxSymPyFEnv$sinpi <- functionOp2("sin(pi * (", "))")
rxSymPyFEnv$tanpi <- functionOp2("tan(pi * (", "))")
rxSymPyFEnv$logspace_add <- binaryOp2(" + ");
rxSymPyFEnv$logspace_sub <- binaryOp2(" - ");
sympyRxFEnv$loggamma <- functionOp("lgamma");
sympyRxFEnv$Abs <- functionOp("abs")
rxSymPyFEnv$log1p <- functionOp2("log(1 + (", "))");
rxSymPyFEnv$log1pmx <- functionBrewx("(log(1 + (<%=x%>))-(<%=x%>))");
rxSymPyFEnv$expm1 <- functionOp2("(exp(", ")-1)");
rxSymPyFEnv$log10 <- function(x){
    if (x == "E" || x == "exp(1)" || x == "e"){
        return("1/log(10)")
    } else {
        return(paste0("(log(", x, ")/log(10))"))
    }
}
rxSymPyFEnv$choose <- functionBrewxy("(factorial(<%=x%>)/(factorial(<%=y%>)*factorial((<%=x%>)-(<%=y%>))))");
rxSymPyFEnv$lchoose <- functionBrewxy("(log(gamma((<%=x%>)+1))-log(gamma((<%=y%>)+1))-log(gamma((<%=x%>)-(<%=y%>)+1)))");

```

**Comment by mattfidler** [comment]
The left if the `sympy` function and the right is the `R` function.

**Comment by Marlin-Na** [comment]
Many of these functions are currently not supported in formula, but supported with S4 method dispatch.

Currently supported functions in your list:
- choose
- gamma
- sinpi
- cospi
- tanpi
- abs

Functions that will be implemented in future:
- log10  as log(x)/log(10)
- log2    as log(x)/log(2)
- log1p  as log(1 + x)
- expm1 as exp(x) - 1
- lgamma  as  log(abs(gamma(x)))
- digamma
- trigamma

These listed functions have corresponding definition in base R. There might be other ones that are possible to implement. And they will be supported in parsing formula eventually.

For your specific example, currently you can use:
```r
log(abs(gamma(S("x"))))
```

**Comment by isuruf** [comment]
@Marlin-Na, how about using symengine's parser?

**Comment by Marlin-Na** [comment]
@isuruf I think symengine's parser does not support `lgamma` directly? 
```
S("lgamma(23)")
# (FunctionSymbol)        lgamma(23)
S("gamma(32)")
# (Integer)       8222838654177922817725562880000000
S("log(abs(gamma(32)))")
# (Log)   log(8222838654177922817725562880000000)
```

**Comment by isuruf** [comment]
Ah, yes. Does `loggamma(23)` work?

**Comment by mattfidler** [comment]
I wasn't clear there was a difference:

```r
> S("lgamma(x)")
(FunctionSymbol)	lgamma(x)
> S(~lgamma(x))
Error in s4basic_parse(x, check_whole_number = TRUE) : 
  Evaluation error: Unable to parse lgamma(x).
```
So I suppose the preferred syntax is `S("")`, correct?

**Comment by mattfidler** [comment]
```R
> S("loggamma(10)")
(LogGamma)	loggamma(10)
```

**Comment by Marlin-Na** [comment]
@isuruf Yes, it works. Then possibly I can implement `lgamma` as 
```
tmp <- S("loggamma(a)")
subs(tmp, "a", x)
```

**Comment by mattfidler** [comment]
Is there some table of symengine syntax so I can access the functions and do the translations directly?

**Comment by isuruf** [comment]
Not really, but you can have a look at https://github.com/symengine/symengine/blob/master/symengine/parser/parser.h#L64-L168

**Comment by Marlin-Na** [comment]
> So I suppose the preferred syntax is S(""), correct?

@mattfidler `S` function converts a R object to a symengine object. It can be a character vector, double value, integer, formula, "Basic" object, or a quoted R expression (not supported yet).

For character vector, it will use symengine's default parser to parse the string. For double value or integer, it will convert to symengine object. For a formula, it will try to parse the formula as a symengine object.

For your application and for a programmable approach in general, you should avoid using formula. Since a formula usually comes from user input and it is complex to construct such a thing. I would suggest you use normal R function when possible, or you can use symengine's parser and `subs` the argument.

For R functions, I intend to support most of the `Math@groupMembers` and `Arith@groupMembers`.

**Comment by mattfidler** [comment]
Thanks.  For now, I will implement using `S("")`
