### ISSUE TITLE
Table of constants in symengine

### ISSUE THREAD

**Issue by mattfidler** [symengine/symengine.R#38]
Some constants are reserved in symengine;  An example is below: 

```R
> S("e")
(Constant)	exp(1)
```

Is there a table of reserved constants?

**Comment by Marlin-Na** [comment]
These are special cases that I am aware of, there might be missing ones:

```
S("I")
S("pi")
S("E")
S("EulerGamma")
S("Catalan")
S("GoldenRatio")
S("inf")
S("nan")
```
You can use `Symbol` instead of `S` if you want a Symbol.

**Comment by mattfidler** [comment]
Thanks!
