### ISSUE TITLE
Integration with Other Packages

### ISSUE THREAD

**Issue by mattfidler** [symengine/symengine.R#5]
Hi,

I saw this package was being developed, and was wondering what time timelines are to put this out on CRAN.

I use sympy through `SnakeCharmR` in `RxODE`.  Can I use sympy expressions directly with symengine? (which is what I produce currently).

I would like to experiment to see if I can use this package for RxODE.

Also are you considering OpenMP support?

**Comment by isuruf** [comment]
@mattfidler, symengine isn't fully featured as sympy is. What functionality do you use from sympy? 

> Can I use sympy expressions directly with symengine? (which is what I produce currently).

sympy is python and symengine is written in C++ and have bindings for C, Python and now R. So, converting from sympy python to symengine C++ is possible, but will take some work.

> I would like to experiment to see if I can use this package for RxODE.

Are you using sympy to generate C code for an ODE function and the jacobian, etc.? What are the sympy functions you use?

**Comment by mattfidler** [comment]
I use:
- Expansion (which is shown to work in the example)
- differentiation for jacobian/forward senstivitiy analysis (and then convert to ODE)
- symbolic matrix multipication and element wise differentiation.

I believe that all this is availble for SymEngine, right?

**Comment by isuruf** [comment]
Yes, they are. Since you've got `sympy` working, I'd suggest first using `symengine.py` through python to experiment. A python line like `from sympy import Symbol` becomes `from symengine import Symbol`.
If `symengine.py` through `SnakeCharmR` works for you, then you can switch to `symengine.R` which will be lightweight (no need of python) and fast (avoid python runtime costs)

**Comment by mattfidler** [comment]
I will expermiment.

Do you know if there will some of this functionality be available from a C/R interface so I can call it from compiled code (and possibly use OpenMP to speed up calculation)?  

Just curious.

The only other thing I'm unsure of how to do is to clear the symbols etc from the call stack.  I knew how to do this in python, but am unsure how to clean the symengine Symbols/Functions.  I looked in the C documentation before, but didn't see anything.

**Comment by isuruf** [comment]
> Do you know if there will some of this functionality be available from a C/R interface so I can call it from compiled code (and possibly use OpenMP to speed up calculation)?

Goal is to provide everything in the C API of symengine. What kind of calculations do you hope to speedup? For example, elementwise differentiation can be parallelized naively, but single element differentiation can be hard and needs to be implemented in libsymengine.

> The only other thing I'm unsure of how to do is to clear the symbols etc from the call stack.

Hmm, I don't understand. Can you clarify?

**Comment by mattfidler** [comment]
> What kind of calculations do you hope to speedup?

So calculating the jacobian loads all the equations and then calculates multiple derivatives.  This is an easy parallelization, I believe.  However, in windows and other implementations R parallelization is very very bad (compared to parallization in libsymengine).

> Can you clarify?

I noticed with 200 or more ODE compartments and large expressions the memory of sympy can expand.  This can be fixed by removing the variable associated with Symbols and Functions, but I wasn't sure how to do this in C.

**Comment by isuruf** [comment]
> I noticed with 200 or more ODE compartments and large expressions the memory that sympy uses can be very large. This can be fixed by removing the variable associated with Symbols and Functions. In symengine, I am unsure how to free these variables.

I still don't understand. Is this a python issue or an R issue? symengine and sympy are both reference-counted and once an expression's reference-count is 0, it'll be freed.

**Comment by mattfidler** [comment]
>Is this a python issue or an R issue?

Removing the variables in python and garbage collecting (in python) removed the memory.  This effectively had the expression's reference count be 0.  

I had to remove the expressions in python for this to occur, and thought I would have to do the same in C, but if this is not the case, then I am mistaking.

**Comment by isuruf** [comment]
Okay. So, the symengine objects are tied to the lifetime of the R object. Manually clearing the R object should do what you want

**Comment by Marlin-Na** [comment]
Hi @mattfidler , the R interface to symengine is still in early stage of development. I personally expect it should be available on CRAN during this summer.

**Comment by mattfidler** [comment]
Thanks.  Its a goal to work for.  It allows me some time to test if symengine will work instead of sympy.  

Can I drop sympy entirely if I use symengine in python?

**Comment by isuruf** [comment]
> Can I drop sympy entirely if I use symengine in python?

For your use-case, yes.

**Comment by mattfidler** [comment]
Would you be interested in an R domain specific language that translates R syntax to python syntax for this project?
]

**Comment by Marlin-Na** [comment]
@mattfidler Hi, I am not sure I understand your question. Do you mean calling python (e.g. sympy) from R?

**Comment by mattfidler** [comment]
It converts R say `x^2+2` to python `x**2+2` using R's parser.

It is talked about here http://adv-r.had.co.nz/dsl.html

I was assuming that symengine still uses Python syntax.

**Comment by Marlin-Na** [comment]
@mattfidler In R we can do:
```R
library(symengine)
x <- Symbol("x")
x ^2L + 2L
# (Add)	2 + x^2
```
We define methods of operators and math functions working with symengine objects, and they should match R user's expectation.

SymEngine does have a parser which parse expression from string. For example:
```R
> S("x ^ 2 + 4y")
# (Add)	4*y + x^2
```
The string is however not guaranteed to be a valid R expression.
