### ISSUE TITLE
Incorporate with a numeric ODE solver

### ISSUE THREAD

**Issue by Marlin-Na** [symengine/symengine.R#55]
SymEngine can convert Basic object to C code string. Then we can easily incorporate them with an existing numeric ODE solver. There are existing R packages that can help compiling C/C++ source code with ODE solver and run them.

Candidates are:
- cOde, https://github.com/dkaschek/cOde
- odeintr, https://github.com/thk686/odeintr

**Comment by mattfidler** [comment]
You could also use RxODE;  As a bonus it already uses symengine

**Comment by mattfidler** [comment]
It also converts R to C/C++
