### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by Marlin-Na** [symengine/symengine.R#60]
Checklist:

- [x] Check the `DESCRIPTION` file for authors, license, etc.
- [x] Simplify the `README`.
- [x] Proof read all the documentation.
- [x] Write a simple vignette listing some basic usage.
- [x] Check the package with `R CMD check --as-cran`.
- [ ] Check the package on [r hub](https://builder.r-hub.io/)
- [x] Check the package on CRAN's [win-builder](https://win-builder.r-project.org/).
- [x] Bump version in `DESCRIPTION`.

**Comment by Marlin-Na** [comment]
We should also consider submitting to https://ropensci.org/ which will review the package.

**Comment by mattfidler** [comment]
Is there anything I can do to help you guys?

**Comment by isuruf** [comment]
@Marlin-Na, I can help as well.

**Comment by Marlin-Na** [comment]
Thanks @isuruf @mattfidler , I will get some time this weekend to do a final review and submit it.

**Comment by mattfidler** [comment]
Thank you so much @Marlin-Na

**Comment by Marlin-Na** [comment]
The package has now been submitted on CRAN for review. The next step is to wait for CRAN's response and see if there are issues with building/checking.

**Comment by mattfidler** [comment]
Thank you.  I saw it on CRAN-incoming.

**Comment by Marlin-Na** [comment]
Finally on its way to CRAN

**Comment by mattfidler** [comment]
Horray!

**Comment by isuruf** [comment]
Looks like it was removed. https://cran.r-project.org/web/packages/symengine/index.html

Let me know how I can help

**Comment by Marlin-Na** [comment]
Now it has been resubmitted and accepted.

**Comment by mattfidler** [comment]
Awesome!  Thanks again @Marlin-Na.  I will be watching the CRAN tests in the next while

**Comment by mattfidler** [comment]
Apparently there may be a problem that might kick it off cran again:

https://cran.r-project.org/web/checks/check_results_symengine.html

For some reason Mac OS isn't detecting cmake.

**Comment by mattfidler** [comment]
Nevermind, that was for the previous version.
