### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by irexyc** [symengine/symengine.R#7]
I try to install it both on macOS and debian9, but both are failed.

On macOS 10.12.2, the installation logs 

> devtools::install_github("Marlin-Na/symengine.R")
Downloading GitHub repo Marlin-Na/symengine.R@master
from URL https://api.github.com/repos/Marlin-Na/symengine.R/zipball/master
Installing symengine
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/yw/h3pq4r2s52z_byw7yw29g78w0000gn/T/RtmpMUhMpB/devtools2c2f6f0ba117/Marlin-Na-symengine.R-4270b2e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘symengine’ ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG `cmake --find-package -DNAME=SymEngine -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=COMPILE` -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
CMake Error: Problem processing arguments. Aborting.

clang: error: no such file or directory: 'SymEngine'
clang: error: no such file or directory: 'not'
clang: error: no such file or directory: 'found.'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘symengine’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/symengine’
Installation failed: Command failed (1)

---------------------------------------------------------------------------------------------
On debian9, the installation logs:

> devtools::install_github("Marlin-Na/symengine.R", ref='317ad1c')
Downloading GitHub repo Marlin-Na/symengine.R@317ad1c
from URL https://api.github.com/repos/Marlin-Na/symengine.R/zipball/317ad1c
Installing symengine
'/usr/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/RtmprmOZUH/devtools7b5b60adc68b/Marlin-Na-symengine.R-317ad1c'  \
  --library='/home/cx/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package ‘symengine’ ...
** libs
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG `cmake --find-package -DNAME=SymEngine -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=COMPILE` -I"/home/cx/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/stretch/r-base-3.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
CMake Error: Problem processing arguments. Aborting.

/usr/lib/R/etc/Makeconf:168: recipe for target 'RcppExports.o' failed
g++: error: SymEngine: no such file or directory
g++: error: not: no such file or directory
g++: error: found.: no such file or directory
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘symengine’
* removing ‘/home/cx/R/x86_64-pc-linux-gnu-library/3.4/symengine’
Installation failed: Command failed (1)

**Comment by Marlin-Na** [comment]
Sorry, currently you will need to install the symengine C++ library manually. Please see the instruction at https://github.com/symengine/symengine . I will update the README tomorrow.
