### ISSUE TITLE
R aborted when solving polynomial

### ISSUE THREAD

**Issue by hwborchers** [symengine/symengine.R#94]
I am trying to apply symengine::solve to find roots of a non-cyclotomic polynomial of degree 7:

    library(symengine)
    ## SymEngine Version: 0.6.0

    x <- Symbol("x")
    p7 <- x^7L + 2L*x^5L - 12L*x^4L - 12L*x^3L + 2L*x^2L + 1L

    solve(p7, x)

and the R process stops with the following message:

    R Session Aborted
    R encountered a fatal error.
    The session was terminated.

Whatever happens to the SymEngine process, the connected R process should never die!

**Comment by Marlin-Na** [comment]
Thanks for reporting. This should be fixed on master branch now (except for Windows).
